### ISSUE TITLE
Coordinate (-1, 1) is printed as (-1,-1)

### ISSUE THREAD

**Issue by YouriMulder** [R2D2-2019/mapping#15]
Jasper van Poelgeest pointed out that there is an issue with the printing of all the maps.

![afbeelding](https://user-images.githubusercontent.com/26016541/57866994-9f552000-7800-11e9-9021-67b28a9c1899.png)

**Comment by YouriMulder** [comment]
Created a pull request to fix this issue
https://github.com/R2D2-2019/mapping/pull/16

**Comment by Dwarf-Nebula** [comment]
Pull request is accepted
